language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: d82fa8664c37364fed6df18ab18857067579dba6
 local_dir: dist
 on:
   branch: master